name: CI

on:
  pull_request:

jobs:
  check-version:
    name: Is NPM version untagged?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Hente STYRBORD_VERSION
        run: echo "STYRBORD_VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - run: echo $STYRBORD_VERSION
      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ env.STYRBORD_VERSION }}
      - run: exit 1
        if: steps.check-tag.outputs.exists == 'true'
  run-linters:
    name: Pretty / Lint / Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build
